name: v_school
description: "this app for school management with teachers , students and parents"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # screen util
  flutter_screenutil: ^5.9.3
  # routes
  go_router: ^14.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Regular.ttf
           style: normal
           weight: 400
         - asset: assets/fonts/Poppins/Poppins-Medium.ttf
           style: normal
           weight: 500
         - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
           style: normal
           weight: 600
         - asset: assets/fonts/Poppins/Poppins-Bold.ttf
           style: normal
           weight: 700
         - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
           style: normal
           weight: 800
         - asset: assets/fonts/Poppins/Poppins-Light.ttf
           style: normal
           weight: 300
         - asset: assets/fonts/Poppins/Poppins-Thin.ttf
           style: normal
           weight: 100
         - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
           style: normal
           weight: 200
         - asset: assets/fonts/Poppins/italic/Poppins-Italic.ttf
           style: italic
           weight: 400
         - asset: assets/fonts/Poppins/italic/Poppins-MediumItalic.ttf
           style: italic
           weight: 500
         - asset: assets/fonts/Poppins/italic/Poppins-SemiBoldItalic.ttf
           style: italic
           weight: 600
         - asset: assets/fonts/Poppins/italic/Poppins-BoldItalic.ttf
           style: italic
           weight: 700
         - asset: assets/fonts/Poppins/italic/Poppins-ExtraBoldItalic.ttf
           style: italic
           weight: 800
         - asset: assets/fonts/Poppins/italic/Poppins-LightItalic.ttf
           style: italic
           weight: 300
         - asset: assets/fonts/Poppins/italic/Poppins-ThinItalic.ttf
           style: italic
           weight: 100
         - asset: assets/fonts/Poppins/italic/Poppins-ExtraLightItalic.ttf
           style: italic
           weight: 200
